### ISSUE TITLE
Some questions about Passport

### ISSUE THREAD

**Issue by johnnynanjiang** [0xpass/passport-demo#2]
Hi Passport,

Your decentralized MPC looks very promising, just a couple of questions, hope it is ok to put them here as there is no `discussion` section.

1. Would it be open source?
2. Would the network be fully decentralized and permissionless?
3. How the network guarantee there is no collusion among nodes?
4. How the consensus works? Is it like n of m, or a certain percentage of the nodes?
5. How to manage nodes joining and leaving to make sure key shares won't be impacted?
6. The programmable feature is awesome, is code (Passport Lambdas) executed on nodes or smart contracts?
8. Does the architecture provide hooks for 3rd parties to integration their solutions, e.g. a hook at pre-sining point so that security solutions can hook into this point to do address scanning etc.
9. There is an event handler in the architecture, is it a centralized server or something?
10. Is there tokenomics for Passport, how it looks like?

Thanks and regards,
Johnny

**Comment by thecskc** [comment]
Hey Johnny, 

Great questions! 

1. Passport is not open source at this moment, but we do have this in our plans. We're looking to also create forms of public verifiability through enclave attestations. 

2. The network is distributed but permissioned - currently 0xPass (our company) runs the nodes and decides who can become a node operator. This allows us to prioritize performance. We're focused on progressive decentralization and will be looking at multiple mechanisms such as offloading decision making to a DAO, bringing in external node operators in a controlled manner, etc. However, our company can't really interfere with any critical operations since they're shielded with MPC and enclaves. 

3. There is a degree of trust placed on the nature of the node operators although the network is distributed. That is just the nature of our permissioned network today and it's a tradeoff we're making to optimize for UX and performance. 

Having said that, there are ways we can ensure direct user participation and identifying colluding/malicious operators. These are network designs we will be exploring in the mid-term (not the immediate term). 

Again a lot of these solutions are subjective and depends on the trust assumptions and the threat model your solution is willing to take. For example - Password-protected secret sharing will ensure direct participation of the user requiring knowledge of a passcode, whereas public verifiability/cheater identification protocols combined with economic incentives can be used to incentivize node operators to be more "honest". 

4. We have a 2 of 3 MPC scheme right now 

5. This is a question as we expand the network and we've worked on this as part of our Halides design (I've shared our docs with you already). We'll be releasing a litepaper on this soon as well. 

6. Lambdas are executed on the nodes, with critical pieces shielded via enclaves!

7.  You can do this with the lambdas 

8. Our architecture has changed a little. Requests are processed by the nodes. All of the authenticatin/user verification happens via enclaves so the nodes cannot interfere. 

9. TBD!

**Comment by johnnynanjiang** [comment]
Thanks @thecskc for your detailed and sensible answers, appreciate them.

They sound very promising and aligned with our vision, and I'm keen to dig into Passport in more detail with help  from you guys 🙌
